import Head from 'next/head'
import Image from 'next/image'
import {useTheme} from 'next-themes'
import { Inter } from '@next/font/google'
import DarkModeToggle from "react-dark-mode-toggle"
import styles from 'styles/Home.module.scss'
import ThemeToggle from 'components/ThemeToggle'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
const {theme, setTheme} = useTheme()
const isDarkMode = theme === 'dark';

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex p-3 bg-white dark:bg-zinc-900 flex-1 h-screen">
        <div className='flex flex-1 justify-end items-start'>
          <ThemeToggle />
        </div>
      </main>
    </>
  )
}
